/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaymentOption.java
 *
 * Created on Nov 12, 2011, 3:13:10 PM
 */
package view;
import javax.swing.*;
import java.awt.*;
import model.Cart;
import model.Drink;
import model.Food;
/**
 *
 * @author Jamel Jenkins
 */
public class PaymentOption extends javax.swing.JPanel {
public static JDialog cashframe;
public static JDialog debitframe;
public static String[] types = {"Visa", "Discover", "MasterCard", "AmericanExpress"};
public static JLabel cardPics = new JLabel();
public static JLabel debit = new JLabel("Debit/Credit Cards");
public static JLabel billing = new JLabel("Billing Information");
public static JLabel name = new JLabel("Name on Card:");
public static JTextField nameField = new JTextField(30);
public static JTextField numberField = new JTextField(30);
public static JTextField securityField = new JTextField(3);
public static JLabel card = new JLabel("Card Type:");
public static JComboBox cardType = new JComboBox(types);
public static JLabel Expiration = new JLabel("Expiration Date:");
public static String[] months = {"1", "2", "3", "4", "5", "6", "7","8", "9", "10", "11", "12"};
public static JComboBox expMonth = new JComboBox(months);
public static String[] years = {"2011", "2012", "2013", "2014", "2015", "2016", "2017"};
public static JComboBox expYear = new JComboBox(years);
public static JLabel cardNumber = new JLabel("Card Number:");
public static JLabel cardSecure = new JLabel("Card Security Number:");
public static Cart cart;
    /** Creates new form PaymentOption */
    public PaymentOption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selection = new javax.swing.ButtonGroup();
        Cash = new javax.swing.JRadioButton();
        Debit = new javax.swing.JRadioButton();

        Selection.add(Cash);
        Cash.setFont(new java.awt.Font("AR DARLING", 0, 18)); // NOI18N
        Cash.setText("Cash");
        Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashActionPerformed(evt);
            }
        });

        Selection.add(Debit);
        Debit.setFont(new java.awt.Font("AR DARLING", 0, 18)); // NOI18N
        Debit.setText("Debit/Credit");
        Debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Cash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(Debit)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cash)
                    .addComponent(Debit))
                .addContainerGap(599, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashActionPerformed
      int cashPane = JOptionPane.showConfirmDialog(
                      cashframe, "Are You Sure That You Want To Pay In Cash",
                      "Payment Option",
                      JOptionPane.YES_NO_OPTION);   
      
      if (cashPane == JOptionPane.YES_OPTION) {
     // JOptionPane.showMessageDialog(null,"Your Total is: $" + cart.getTotal());
      JOptionPane.showMessageDialog(null,"The Waitress/Waiter Will Be There Shortly To Receive Your Payment!"
              + " Thank You for Choosing Cnerds Cafe'");
    RMSGui.paymentScrollPane.setVisible(false);
    RMSGui.PaymentLogo.setVisible(false);
    RMSGui.confirm2.setVisible(false);
    RMSGui.confirmback.setVisible(false);
    RMSGui.confirm.setVisible(false);
    RMSGui.Logo.setVisible(true);
    RMSGui.AdminLogin.setVisible(true);
    RMSGui.enterMenu.setVisible(true);
    RMSGui.Logo2.setVisible(false);
    RMSGui.home.setVisible(false);
    RMSGui.Logo3.setVisible(false);
    RMSGui.home2.setVisible(false);
    RMSGui.back.setVisible(false);
    RMSGui.viewback.setVisible(false);
    RMSGui.viewcart.setVisible(false);
    RMSGui.drinks.setVisible(false);
    RMSGui.separator.setVisible(false);
    RMSGui.breakfast.setVisible(false);
    RMSGui.lunch.setVisible(false);
    RMSGui.dinner.setVisible(false);
    RMSGui.desserts.setVisible(false);
    RMSGui.MenuLogo.setVisible(false);
    RMSGui.CartLogo.setVisible(false);
    RMSGui.viewScrollPane.setVisible(false);
    RMSGui.CarryOut.setVisible(false);
    RMSGui.dineIn.setVisible(false);
    RMSGui.Reservations.setVisible(false);
    RMSGui.appetizers.setVisible(false);
    RMSGui.appetizersPane.setVisible(false);
    RMSGui.breakfastPane.setVisible(false);
    RMSGui.lunchPane.setVisible(false);
    RMSGui.dinnerPane.setVisible(false);
    RMSGui.dessertPane.setVisible(false);
    RMSGui.drinksPane.setVisible(false);
    repaint();
      }
    }//GEN-LAST:event_CashActionPerformed

    private void DebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitActionPerformed
     int cashPane = JOptionPane.showConfirmDialog(
                      cashframe, "Are You Sure That You Want To Pay With a Debit/Credit Card",
                      "Payment Option",
                      JOptionPane.YES_NO_OPTION);   
     if (cashPane == JOptionPane.YES_OPTION) {
         RMSGui.confirmback.setVisible(true);
         debit.setVisible(true);
         debit.setLocation(20,50);
         debit.setSize(200,100);
         debit.setForeground(new java.awt.Color(0, 0, 0));
         debit.setFont(new java.awt.Font("AR DARLING", 0, 18));
         add(debit);
         cardPics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/CreditCardLogos.png")));
         cardPics.setVisible(true);
         cardPics.setLocation(250,55);
         cardPics.setSize(200,100);
         add(cardPics);
         name.setVisible(true);
         name.setLocation(60,100);
         name.setSize(200,100);
         name.setForeground(new java.awt.Color(0, 0, 0));
         name.setFont(new java.awt.Font("AR DARLING", 0, 16));
         add(name);
         nameField.setVisible(true);
         nameField.setLocation(170,143);
         nameField.setSize(300,20);
         add(nameField);
         cardType.setVisible(true);
         cardType.setLocation(155,173);
         cardType.setSize(100,20);
         add(cardType);
         card.setVisible(true);
         card.setLocation(60,130);
         card.setSize(200,100);
         card.setForeground(new java.awt.Color(0, 0, 0));
         card.setFont(new java.awt.Font("AR DARLING", 0, 16));
         add(card);
         cardNumber.setVisible(true);
         cardNumber.setLocation(60,160);
         cardNumber.setSize(200,100);
         cardNumber.setForeground(new java.awt.Color(0, 0, 0));
         cardNumber.setFont(new java.awt.Font("AR DARLING", 0, 16));
         add(cardNumber);
         numberField.setVisible(true);
         numberField.setLocation(165,203);
         numberField.setSize(300,20);
         add(numberField);
         Expiration.setVisible(true);
         Expiration.setLocation(60,190);
         Expiration.setSize(200,100);
         Expiration.setForeground(new java.awt.Color(0, 0, 0));
         Expiration.setFont(new java.awt.Font("AR DARLING", 0, 16));
         add(Expiration);
         expMonth.setVisible(true);
         expMonth.setLocation(183,233);
         expMonth.setSize(40,20);
         add(expMonth);
         expYear.setVisible(true);
         expYear.setLocation(225,233);
         expYear.setSize(70,20);
         add(expYear);
         cardSecure.setVisible(true);
         cardSecure.setLocation(60,220);
         cardSecure.setSize(200,100);
         cardSecure.setForeground(new java.awt.Color(0, 0, 0));
         cardSecure.setFont(new java.awt.Font("AR DARLING", 0, 16));
         add(cardSecure);
         securityField.setVisible(true);
         securityField.setLocation(230,263);
         securityField.setSize(70,20);
         add(securityField);
         billing.setVisible(true);
         billing.setLocation(20,265);
         billing.setSize(200,100);
         billing.setForeground(new java.awt.Color(0, 0, 0));
         billing.setFont(new java.awt.Font("AR DARLING", 0, 18));
         add(billing);
         repaint();
     }
    }//GEN-LAST:event_DebitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cash;
    private javax.swing.JRadioButton Debit;
    private javax.swing.ButtonGroup Selection;
    // End of variables declaration//GEN-END:variables
}
