/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaymentOption.java
 *
 * Created on Nov 12, 2011, 3:13:10 PM
 */
package view;
import javax.swing.*;
import java.awt.*;
import model.Cart;
/**
 *
 * @author Jamel Jenkins
 */
public class PaymentOption extends javax.swing.JPanel {
public static JDialog cashframe;
public static JDialog debitframe;
public static Cart cart;
    /** Creates new form PaymentOption */
    public PaymentOption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selection = new javax.swing.ButtonGroup();
        Cash = new javax.swing.JRadioButton();
        Debit = new javax.swing.JRadioButton();

        Selection.add(Cash);
        Cash.setFont(new java.awt.Font("AR DARLING", 0, 18)); // NOI18N
        Cash.setText("Cash");
        Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashActionPerformed(evt);
            }
        });

        Selection.add(Debit);
        Debit.setFont(new java.awt.Font("AR DARLING", 0, 18)); // NOI18N
        Debit.setText("Debit/Credit");
        Debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Cash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(Debit)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cash)
                    .addComponent(Debit))
                .addContainerGap(471, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashActionPerformed
      int cashPane = JOptionPane.showConfirmDialog(
                      cashframe, "Are You Sure That You Want To Pay In Cash",
                      "Payment Option",
                      JOptionPane.YES_NO_OPTION);   
      
      if (cashPane == JOptionPane.YES_OPTION) {
      //JOptionPane.showMessageDialog(null,"Your Total is: $" + cart.getTotal());
      JOptionPane.showMessageDialog(null,"The Waitress/Waiter Will Be There Shortly To Receive Your Payment!"
              + " Thank You for Choosing Cnerds Cafe'");
    RMSGui.paymentScrollPane.setVisible(false);
    RMSGui.PaymentLogo.setVisible(false);
    RMSGui.confirm2.setVisible(false);
    RMSGui.confirmback.setVisible(false);
    RMSGui.confirm.setVisible(false);
    RMSGui.Logo.setVisible(true);
    RMSGui.AdminLogin.setVisible(true);
    RMSGui.enterMenu.setVisible(true);
    RMSGui.Logo2.setVisible(false);
    RMSGui.home.setVisible(false);
    RMSGui.Logo3.setVisible(false);
    RMSGui.home2.setVisible(false);
    RMSGui.back.setVisible(false);
    RMSGui.viewback.setVisible(false);
    RMSGui.viewcart.setVisible(false);
    RMSGui.drinks.setVisible(false);
    RMSGui.separator.setVisible(false);
    RMSGui.breakfast.setVisible(false);
    RMSGui.lunch.setVisible(false);
    RMSGui.dinner.setVisible(false);
    RMSGui.desserts.setVisible(false);
    RMSGui.MenuLogo.setVisible(false);
    RMSGui.CartLogo.setVisible(false);
    RMSGui.viewScrollPane.setVisible(false);
    RMSGui.CarryOut.setVisible(false);
    RMSGui.dineIn.setVisible(false);
    RMSGui.Reservations.setVisible(false);
    RMSGui.appetizers.setVisible(false);
    RMSGui.appetizersPane.setVisible(false);
    RMSGui.breakfastPane.setVisible(false);
    RMSGui.lunchPane.setVisible(false);
    RMSGui.dinnerPane.setVisible(false);
    RMSGui.dessertPane.setVisible(false);
    RMSGui.drinksPane.setVisible(false);
    repaint();
      }
    }//GEN-LAST:event_CashActionPerformed

    private void DebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitActionPerformed
     int cashPane = JOptionPane.showConfirmDialog(
                      cashframe, "Are You Sure That You Want To Pay With a Debit/Credit Card",
                      "Payment Option",
                      JOptionPane.YES_NO_OPTION);   
     if (cashPane == JOptionPane.YES_OPTION) {
         RMSGui.confirmback.setVisible(true);
     }
    }//GEN-LAST:event_DebitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cash;
    private javax.swing.JRadioButton Debit;
    private javax.swing.ButtonGroup Selection;
    // End of variables declaration//GEN-END:variables
}
